/**
 * The starter theme packs, transcribed faithfully from `doot-mockup.html`.
 * To add a theme, define a {@link Theme} here (or in your own module) and
 * register it — see `registry.ts`.
 */
import type { Theme } from './tokens'

/** Doot brand (default): warm cream, coral primary, chunky tactile shadows. */
export const doot: Theme = {
  id: 'doot',
  name: 'Doot',
  description: 'The warm, chunky house style — cream paper, coral accents, hard ink shadows.',
  dark: false,
  tokens: {
    bg: '#FBF1E4',
    bg2: '#FFF8EF',
    surface: '#FFFFFF',
    surface2: '#FFF3E6',
    ink: '#241910',
    inkSoft: '#7A6957',
    mute: '#A4917C',
    line: '#241910',
    lineSoft: '#E7D8C5',
    primary: '#FF5A33',
    primaryInk: '#FFFFFF',
    c1: '#FFC53D',
    c2: '#16C8B5',
    c3: '#FF73B3',
    c4: '#5B79FF',
    c5: '#7DD957',
    radius: '18px',
    radiusLg: '30px',
    bd: '2.5px',
    shadow: '5px 5px 0 rgba(36,25,16,.92)',
    shadowSm: '3px 3px 0 rgba(36,25,16,.9)',
    grain: '.05',
    glow: 'none',
  },
}

/** Cutesie: soft lavender pastels, rounded shapes, gentle shadows. */
export const cutesie: Theme = {
  id: 'cutesie',
  name: 'Cutesie',
  description: 'Soft pastels and rounded shapes for the kawaii and convention crowd.',
  dark: false,
  tokens: {
    bg: '#F4ECFF',
    bg2: '#FBF6FF',
    surface: '#FFFFFF',
    surface2: '#F6EFFF',
    ink: '#4B3A66',
    inkSoft: '#8E7DAE',
    mute: '#B3A6CC',
    line: '#E4D6F7',
    lineSoft: '#EFE6FB',
    primary: '#B98CFF',
    primaryInk: '#3A2960',
    c1: '#9FE6D0',
    c2: '#FFC9A8',
    c3: '#FFA6D5',
    c4: '#A9D3FF',
    c5: '#D7B6FF',
    radius: '22px',
    radiusLg: '34px',
    bd: '2.5px',
    shadow: '5px 6px 0 #E4D6F7',
    shadowSm: '3px 3px 0 #EBDFFA',
    grain: '.03',
    glow: 'none',
  },
}

/** Cyber: dark base, neon accents, sharp edges, glow. */
export const cyber: Theme = {
  id: 'cyber',
  name: 'Cyber',
  description: 'Dark base, neon accents, sharp edges and glow. For game nights and a techy look.',
  dark: true,
  tokens: {
    bg: '#0A0C16',
    bg2: '#101325',
    surface: '#151A2E',
    surface2: '#1B2138',
    ink: '#E9EEFF',
    inkSoft: '#9AA4CC',
    mute: '#6E7AA6',
    line: '#2B3257',
    lineSoft: '#222845',
    primary: '#2FE7CE',
    primaryInk: '#04201C',
    c1: '#FF4D9D',
    c2: '#C6FF4D',
    c3: '#38D1FF',
    c4: '#8A6CFF',
    c5: '#FFD23D',
    radius: '10px',
    radiusLg: '16px',
    bd: '1.5px',
    shadow: '0 0 0 transparent',
    shadowSm: '0 0 0 transparent',
    grain: '.07',
    glow: '0 0 22px',
  },
}

/** Professional: restrained palette, clean sans, subtle soft shadows, no texture. */
export const professional: Theme = {
  id: 'professional',
  name: 'Professional',
  description: 'Restrained palette and subtle motion for classrooms and work settings.',
  dark: false,
  tokens: {
    bg: '#F3F6FB',
    bg2: '#FFFFFF',
    surface: '#FFFFFF',
    surface2: '#F7F9FD',
    ink: '#1B2536',
    inkSoft: '#5C6880',
    mute: '#94A0B6',
    line: '#DEE5F0',
    lineSoft: '#EBEFF6',
    primary: '#2D5BFF',
    primaryInk: '#FFFFFF',
    c1: '#1FA39C',
    c2: '#2D5BFF',
    c3: '#6B7A99',
    c4: '#0FB5A0',
    c5: '#3F6BFF',
    radius: '12px',
    radiusLg: '18px',
    bd: '1.5px',
    shadow: '0 8px 24px rgba(22,34,64,.09)',
    shadowSm: '0 3px 12px rgba(22,34,64,.07)',
    grain: '.015',
    glow: 'none',
  },
}

/** Playful: bright primaries, chunky shapes, bouncy motion, hard offset shadows. */
export const playful: Theme = {
  id: 'playful',
  name: 'Playful',
  description: 'Bright primaries, chunky shapes and hard offset shadows. A general party look.',
  dark: false,
  tokens: {
    bg: '#FFF2CF',
    bg2: '#FFF9E6',
    surface: '#FFFFFF',
    surface2: '#FFF6DA',
    ink: '#221E16',
    inkSoft: '#6B6048',
    mute: '#9C8F6E',
    line: '#221E16',
    lineSoft: '#F0E4BC',
    primary: '#FF3E8F',
    primaryInk: '#FFFFFF',
    c1: '#FFD028',
    c2: '#34C7FF',
    c3: '#6BE06B',
    c4: '#FF6B3D',
    c5: '#B36BFF',
    radius: '20px',
    radiusLg: '32px',
    bd: '3px',
    shadow: '6px 6px 0 #221E16',
    shadowSm: '3px 3px 0 #221E16',
    grain: '.05',
    glow: 'none',
  },
}
