import { chromium } from 'playwright'
const BASE = process.env.B || 'http://localhost:3000'
const b = await chromium.launch()
const tv = await b.newContext({ viewport:{width:1280,height:800} }); const host = await tv.newPage()
await host.goto(`${BASE}/host/circuit-cypher`,{waitUntil:'networkidle'})
await host.waitForSelector('.code',{timeout:30000}); const code=(await host.textContent('.code')).trim()
const phone = await b.newContext({ viewport:{width:390,height:844}, isMobile:true }); const p = await phone.newPage()
await p.goto(`${BASE}/play/${code}`); await p.waitForSelector('input')
await p.locator('input').last().fill('Ana'); await p.click('button:has-text("Join")')
await p.waitForSelector('text=You are in',{timeout:30000})
await host.click('button:has-text("Start game")'); await host.waitForTimeout(800)
await host.locator('button:has-text("Collect answers"),button:has-text("Open voting")').first().click()
await host.waitForTimeout(1200)
// reload + REJOIN mid-round (same name)
await p.reload({ waitUntil:'networkidle' }); await p.waitForSelector('input',{timeout:20000})
await p.locator('input').last().fill('Ana'); await p.click('button:has-text("Join")')
await p.waitForTimeout(4000)
console.log('after REJOIN — body:', (await p.locator('body').innerText()).replace(/\n+/g,' | ').slice(0,160))
console.log('bars-input:', await p.locator('.bars-input').count())
await b.close()
