/**
 * "Decks by Doot": the content for the public, remixable starter decks, one entry per
 * deck. The seed script (seed-decks.mjs) upserts these (keyed by name) as public +
 * remixable decks owned by a stable Doot account, so anyone can remix a pool game with
 * them. Content is original, family-friendly, and deliberately free of em dashes.
 *
 * Column keys match each game's conventional pool columns (see docs/decks.md), so a deck
 * feeds its game with no per-row mapping: prompt games use one text column, the typed
 * games use their named columns (question/truth, prompt/answer/unit, prompt/options/correct,
 * category/word). A `game` field records the intended game (the seed script does not need
 * it, but it documents intent and could drive a future "decks for this game" view).
 *
 * Trivia answers are checked general-knowledge facts. `correct` for multiple choice is
 * 1-based (1 = the first option).
 */

const PROMPT = [{ key: 'prompt', label: 'Prompt', type: 'text' }]
const INITIALISM = [{ key: 'prompt', label: 'Initialism', type: 'text' }]
const FRAME = [{ key: 'frame', label: 'Dilemma (use {x} for the blank)', type: 'text' }]
const TEMPLATE = [{ key: 'template', label: 'Story template (use {token} blanks)', type: 'text' }]
const FACT = [
  { key: 'question', label: 'Question (use ___ for the blank)', type: 'text' },
  { key: 'truth', label: 'Answer', type: 'text' },
]
const NUMBER = [
  { key: 'prompt', label: 'Question', type: 'text' },
  { key: 'answer', label: 'Answer', type: 'number' },
  { key: 'unit', label: 'Unit', type: 'text' },
]
const CHOICE = [
  { key: 'prompt', label: 'Question', type: 'text' },
  { key: 'options', label: 'Options (separate with |)', type: 'text' },
  { key: 'correct', label: 'Correct (1 = first option)', type: 'number' },
]
const SECRET = [
  { key: 'category', label: 'Category (shown to all)', type: 'text' },
  { key: 'word', label: 'Secret word', type: 'text' },
]

const p = (...lines) => lines.map((prompt) => ({ prompt }))
const f = (...lines) => lines.map((frame) => ({ frame }))
const t = (...lines) => lines.map((template) => ({ template }))

export const DECKS = [
  // ── Quip Clash (fill-the-blank prompts) ────────────────────────────────────
  {
    game: 'quip-clash',
    name: 'Quip Clash: Party Pack',
    kind: 'prompt',
    description: 'Fill-the-blank prompts for a house party. Loud, silly, and a little chaotic.',
    columns: PROMPT,
    rows: p(
      'The official sport of this party should be: ___',
      'A terrible thing to find in your birthday cake: ___',
      'The real reason the wifi stopped working: ___',
      'The worst possible party theme: ___',
      'A bad name for a cocktail: ___',
      'The most chaotic thing to bring to a potluck: ___',
      'What the host is definitely hiding in the other room: ___',
      'A terrible icebreaker question: ___',
      'The real reason your friend is always late: ___',
      'What aliens would steal from a house party first: ___',
      'A rejected flavor of birthday cake: ___',
      'The worst gift to bring to a white elephant: ___',
      'The strangest thing to be afraid of: ___',
      'What the neighbors think we are doing in here: ___',
      'A terrible name for a pet goldfish: ___',
      'The worst possible karaoke song choice: ___',
      'A snack that should not exist: ___',
      'The most useless item in a survival kit: ___',
      'The worst superpower to have at a party: ___',
      'The real reason the dog keeps staring at you: ___',
      'A terrible name for a brand new holiday: ___',
      'What I refuse to admit I am bad at: ___',
    ),
  },
  {
    game: 'quip-clash',
    name: 'Quip Clash: Office Edition',
    kind: 'prompt',
    description: 'Workplace fill-the-blanks for the team that needs a break from the team-building.',
    columns: PROMPT,
    rows: p(
      'The real reason this meeting could have been an email: ___',
      'A terrible name for a team-building exercise: ___',
      'What I am actually doing when my status says "in a meeting": ___',
      'The worst thing to put in the office fridge: ___',
      'A bad motivational poster slogan: ___',
      'The real reason the printer is jammed again: ___',
      'What the "quick sync" is really about: ___',
      'A terrible idea for casual Friday: ___',
      'The most cursed thing to microwave at work: ___',
      'A bad name for a new work chat channel: ___',
      'The real reason I keep my camera off: ___',
      'The worst thing to reply-all to the whole company: ___',
      'A terrible perk to offer instead of a raise: ___',
      'What HR definitely does not want to hear: ___',
      'A bad excuse for missing the morning standup: ___',
      'The worst possible out-of-office message: ___',
      'A terrible name for the new company mascot: ___',
      'The real reason the coffee machine is "broken": ___',
      'What I pretend to understand in every meeting: ___',
      'The most suspicious thing in the supply closet: ___',
    ),
  },
  {
    game: 'quip-clash',
    name: 'Quip Clash: Sci-Fi and Fantasy',
    kind: 'prompt',
    description: 'For nerds and adventurers. Spells, starships, and very questionable prophecies.',
    columns: PROMPT,
    rows: p(
      'A spell they refuse to teach at wizard school: ___',
      'The worst thing to find on an alien planet: ___',
      'A bad name for a starship: ___',
      'The real reason the wizard is retiring: ___',
      'What the dragon is actually hoarding: ___',
      'A terrible superpower for a space hero: ___',
      'The most useless item in a knight\'s inventory: ___',
      'What the ancient prophecy forgot to mention: ___',
      'A bad slogan for a time machine: ___',
      'The real reason the robots rebelled: ___',
      'The worst potion to drink before a quest: ___',
      'A terrible name for a magic sword: ___',
      'What the chosen one would rather be doing: ___',
      'The strangest thing to teleport by accident: ___',
      'A bad name for an evil overlord: ___',
      'What the spaceship computer says when it gets bored: ___',
      'A terrible enchantment to put on a pair of socks: ___',
      'The real reason the portal closed: ___',
      'What aliens think the leader of Earth is: ___',
      'The worst creature to summon in a hurry: ___',
    ),
  },

  // ── Open Mic (one-liner setups) ────────────────────────────────────────────
  {
    game: 'open-mic',
    name: 'Open Mic: Observational',
    kind: 'prompt',
    description: 'Everyday annoyances, ready for a one-liner. The good stuff hides in the small things.',
    columns: PROMPT,
    rows: p(
      'Write a one-liner about grocery shopping while hungry.',
      'A joke about how nobody knows how to end a video call.',
      'Tell a one-liner about autocorrect ruining your life.',
      'A bit about the snooze button being your best friend.',
      'A joke about pretending you read the terms and conditions.',
      'A one-liner about losing the TV remote.',
      'Tell a joke about small talk in elevators.',
      'A bit about every charger cable being slightly too short.',
      'A one-liner about pretending to look busy.',
      'A joke about the one messy drawer in every kitchen.',
      'Tell a one-liner about stopping the microwave at one second left.',
      'A bit about socks that vanish in the laundry.',
      'A joke about parallel parking with an audience.',
      'A one-liner about the self-checkout machine yelling at you.',
      'Tell a joke about the gym membership you forgot about.',
      'A one-liner about your phone at one percent.',
      'A joke about umbrellas turning inside out.',
      'Tell a one-liner about the printer that never works.',
      'A bit about nobody being able to fold a fitted sheet.',
      'A joke about the group photo where someone always blinks.',
    ),
  },
  {
    game: 'open-mic',
    name: 'Open Mic: Roast',
    kind: 'prompt',
    description: 'Gentle roasts of everyday things. Aim at the situation, not the person next to you.',
    columns: PROMPT,
    rows: p(
      'Roast Mondays in one line.',
      'Write a one-liner roasting traffic.',
      'Roast the concept of fun runs.',
      'A one-liner roasting group projects.',
      'Roast airport security in one line.',
      'Write a polite roast of your phone battery.',
      'Roast hold music in one line.',
      'A one-liner roasting "rise and grind" culture.',
      'Write a one-liner roasting slow walkers.',
      'Roast the weather app for being confidently wrong.',
      'A one-liner roasting overpriced coffee.',
      'Roast the gym in January.',
      'Write a one-liner roasting cliffhanger season finales.',
      'A one-liner roasting your own music taste.',
      'Roast spoilers in one line.',
      'Write a one-liner roasting "quick" meetings.',
      'Roast the printer that never works.',
      'A one-liner roasting motivational posters.',
      'Roast the snooze button (it can take it).',
      'Write a one-liner roasting buffering at the best part.',
    ),
  },

  // ── Backronym (initialisms to redefine) ────────────────────────────────────
  {
    game: 'backronym',
    name: 'Backronym: Tech',
    kind: 'prompt',
    description: 'Tech initialisms begging for a new (and definitely wrong) meaning.',
    columns: INITIALISM,
    rows: p('HTTP', 'HTML', 'USB', 'RAM', 'CPU', 'GPU', 'API', 'URL', 'PDF', 'JPEG', 'GIF', 'RGB', 'HDMI', 'SSD', 'VPN', 'DNS', 'AI', 'SQL', 'CSS', 'IDE', 'LAN', 'OS', 'QR', 'RAM'),
  },
  {
    game: 'backronym',
    name: 'Backronym: Agencies and Slang',
    kind: 'prompt',
    description: 'Real-world initials, from agencies to texting shorthand. Invent the true meaning.',
    columns: INITIALISM,
    rows: p('FBI', 'CIA', 'NASA', 'FDA', 'DMV', 'TSA', 'EPA', 'FCC', 'WHO', 'NATO', 'FIFA', 'NBA', 'NFL', 'PTA', 'HOA', 'LOL', 'BRB', 'IMO', 'TBH', 'FOMO', 'TLDR', 'IRL', 'GG', 'BTW'),
  },

  // ── Most Likely To ─────────────────────────────────────────────────────────
  {
    game: 'most-likely',
    name: 'Most Likely To: Friend Group',
    kind: 'prompt',
    description: 'Point the finger at your favorite people. Pure friend-group chaos.',
    columns: PROMPT,
    rows: p(
      'Most likely to reply to the group chat at 3am.',
      'Most likely to plan a trip and never book it.',
      'Most likely to know a guy who knows a guy.',
      'Most likely to cry at a commercial.',
      'Most likely to start a podcast tonight.',
      'Most likely to adopt a pet on impulse.',
      'Most likely to lose their keys at least once a day.',
      'Most likely to win an eating contest.',
      'Most likely to become internet famous by accident.',
      'Most likely to give a stranger life advice.',
      'Most likely to fall asleep during the movie.',
      'Most likely to quit a fitness plan by Tuesday.',
      'Most likely to have a snack in their bag right now.',
      'Most likely to get everyone lost with a shortcut.',
      'Most likely to say "we should hang out" and never follow up.',
      'Most likely to befriend the waiter.',
      'Most likely to overpack for a weekend trip.',
      'Most likely to have over 9000 unread emails.',
    ),
  },
  {
    game: 'most-likely',
    name: 'Most Likely To: Office',
    kind: 'prompt',
    description: 'For the team that knows exactly who you mean. Keep it kind, keep it funny.',
    columns: PROMPT,
    rows: p(
      'Most likely to schedule a meeting that could be an email.',
      'Most likely to reply-all by accident.',
      'Most likely to bring snacks to every meeting.',
      'Most likely to have 40 browser tabs open.',
      'Most likely to mute themselves and keep talking.',
      'Most likely to become the boss in five years.',
      'Most likely to know every office secret.',
      'Most likely to win employee of the month.',
      'Most likely to take the last coffee and not refill it.',
      'Most likely to work through their lunch break.',
      'Most likely to suggest a team-building trip.',
      'Most likely to have the messiest desk.',
      'Most likely to send a meme at the perfect time.',
      'Most likely to forget to unmute on a call.',
      'Most likely to volunteer for the hard project.',
      'Most likely to fix the printer for everyone.',
      'Most likely to start a side business.',
      'Most likely to keep the office plants alive.',
    ),
  },

  // ── Hivemind (match the crowd) ─────────────────────────────────────────────
  {
    game: 'hivemind',
    name: 'Hivemind: Everyday',
    kind: 'prompt',
    description: 'Obvious-answer prompts where matching the room is the whole game.',
    columns: PROMPT,
    rows: p(
      'Name a color in a traffic light.',
      'Name a piece of furniture in a living room.',
      'Name something you keep in your wallet.',
      'Name a thing you do before bed.',
      'Name a topping people put on toast.',
      'Name a chore nobody likes.',
      'Name something you find in a bathroom.',
      'Name a vegetable kids avoid.',
      'Name a sport played with a ball.',
      'Name a month with 31 days.',
      'Name something with a screen.',
      'Name a drink you have in the morning.',
      'Name a type of weather.',
      'Name a thing you take on a plane.',
      'Name a flavor of ice cream.',
      'Name something you recycle.',
      'Name a tool in a toolbox.',
      'Name something round.',
      'Name a day of the weekend.',
      'Name a pet that is not a dog or cat.',
    ),
  },
  {
    game: 'hivemind',
    name: 'Hivemind: Pop Culture',
    kind: 'prompt',
    description: 'Name the obvious one. The crowd favorite wins, not the clever pick.',
    columns: PROMPT,
    rows: p(
      'Name a famous superhero.',
      'Name a streaming service.',
      'Name a board game.',
      'Name a Disney princess.',
      'Name a video game character.',
      'Name a music genre.',
      'Name a famous wizard.',
      'Name a fast food restaurant.',
      'Name a social media app.',
      'Name a holiday movie.',
      'Name a cartoon dog.',
      'Name a famous detective.',
      'Name a band everyone knows.',
      'Name a candy bar.',
      'Name a sport in the Summer Olympics.',
      'Name a sitcom.',
      'Name a superhero movie franchise.',
      'Name an emoji you use a lot.',
      'Name a talent competition show.',
      'Name a famous painting.',
    ),
  },

  // ── Sketch and Spot (draw prompts) ─────────────────────────────────────────
  {
    game: 'sketch-spot',
    name: 'Sketch and Spot: Animal Antics',
    kind: 'prompt',
    description: 'Animals doing things they absolutely should not. Easy to draw, fun to guess.',
    columns: PROMPT,
    rows: p(
      'A cat wearing tiny boots',
      'A duck with a mustache',
      'A very buff squirrel',
      'A penguin on vacation',
      'A sleepy dinosaur',
      'A frog as a king',
      'A dog detective',
      'A shark eating ice cream',
      'An owl wearing glasses',
      'A turtle racing a snail',
      'A bee in a business suit',
      'A llama at a disco',
      'A hedgehog in a teacup',
      'A crab playing the drums',
      'A fox riding a bicycle',
      'An elephant on a skateboard',
      'A chicken superhero',
      'A snail with a jetpack',
    ),
  },
  {
    game: 'sketch-spot',
    name: 'Sketch and Spot: Absurd Mashups',
    kind: 'prompt',
    description: 'Two things that should never meet. Maximum chaos, minimum drawing skill required.',
    columns: PROMPT,
    rows: p(
      'A toaster that became a knight',
      'A cactus on a date',
      'A cloud that is late for work',
      'A pineapple lifting weights',
      'A robot baking cookies',
      'A vampire at the beach',
      'A potato running a marathon',
      'A ghost trying to use a phone',
      'A banana driving a tank',
      'A snowman on a tropical island',
      'A wizard fixing a computer',
      'A dragon ordering coffee',
      'A pirate ship made of cheese',
      'A unicorn at the gym',
      'A spaceship shaped like a shoe',
      'A mermaid riding a skateboard',
      'A grumpy sandwich',
      'An alien tasting pizza for the first time',
    ),
  },

  // ── Split the Room (dividing dilemmas, {x} is the blank) ────────────────────
  {
    game: 'split-room',
    name: 'Split the Room: Tough Calls',
    kind: 'prompt',
    description: 'Complete the dilemma to divide the room as evenly as you can. {x} is your blank.',
    columns: FRAME,
    rows: f(
      'Would you {x} for a year of free pizza?',
      'Is it ever okay to {x} in public?',
      'Would you give up {x} to be able to fly for one day?',
      'Should it be illegal to {x}?',
      'Would you {x} in front of a live audience for one thousand dollars?',
      'Would you rather always {x} than lose your phone for a week?',
      'Would you let your best friend {x}?',
      'On a first date, is {x} a red flag?',
      'Would you {x} to win an argument forever?',
      'Would you trust someone who {x}?',
      'Would you {x} every Monday for a guaranteed three-day weekend?',
      'Is {x} a fair reason to end a friendship?',
      'Would you eat {x} for a free vacation?',
      'Would you {x} if no one would ever find out?',
      'Should kids be taught to {x} in school?',
      'Would you {x} for front-row seats to anything you want?',
      'Would you rather {x} than wait in any line ever again?',
      'Would you {x} to never sit in traffic again?',
    ),
  },

  // ── Mad Libs (story templates with {token} blanks) ─────────────────────────
  {
    game: 'mad-libs',
    name: 'Mad Libs: Tall Tales',
    kind: 'generic',
    description: 'Story templates with {token} blanks. The blanks are read straight from the tokens.',
    columns: TEMPLATE,
    rows: t(
      'Breaking news: a {adjective} {animal} was seen {verbing} through {place} while shouting {exclaim}.',
      'My dream job is professional {noun} {verbing}. The pay is {adjective} and the hours are full of {plural}.',
      'Recipe for disaster: combine {number} cups of {food}, one {adjective} {noun}, and a very confused {animal}.',
      'The fortune teller said I would {verb} a {adjective} {noun} and become famous by the age of {number}.',
      'Tonight\'s forecast: {adjective} skies with a chance of {plural} and a scattered {animal} or two.',
      'Welcome aboard flight {number}. Please keep your {bodypart} inside the {noun} and enjoy the {food}.',
      'The ad said: tired of {plural}? Try {adjective} new {noun}, now with extra {food}.',
      'Local {animal} learns to {verb}, then immediately uses the power to {verb2} the entire {place}.',
      'My superhero name is The {adjective} {animal}, and my only weakness is {food}.',
      'Diary entry number {number}: today I taught my {animal} to {verb}. It went very {adjective}.',
    ),
  },
  {
    game: 'mad-libs',
    name: 'Mad Libs: Fairy Tale Mix-Up',
    kind: 'generic',
    description: 'Once upon a time, with the important words missing. Fill the {token} blanks.',
    columns: TEMPLATE,
    rows: t(
      'Once upon a time, a {adjective} princess kissed a {animal} and it turned into a {noun}.',
      'The {adjective} dragon guarded a giant pile of {plural} deep inside the {place}.',
      'To break the spell, the hero had to {verb} a {adjective} {noun} before midnight.',
      'The wizard waved his {noun} and shouted {exclaim}, turning the king into a {animal}.',
      'Deep in the {adjective} forest lived a {animal} who ate only {food} and {plural}.',
      'The knight rode a trusty {animal} into battle, armed with a {noun} and {number} {plural}.',
      'Legend says whoever can {verb} the {adjective} stone will rule {place} forever.',
      'The fairy granted three wishes: a {noun}, a {adjective} {animal}, and {number} {plural}.',
    ),
  },

  // ── Fib Finder (question with ___, plus the true answer) ───────────────────
  {
    game: 'fib-finder',
    name: 'Fib Finder: Animal Kingdom',
    kind: 'quiz',
    description: 'Surprising true facts about animals. Invent a believable lie, then spot the truth.',
    columns: FACT,
    rows: [
      { question: 'A group of crows is called a ___.', truth: 'murder' },
      { question: 'A group of rhinos is called a ___.', truth: 'crash' },
      { question: 'A group of jellyfish is called a ___.', truth: 'smack' },
      { question: 'A group of porcupines is called a ___.', truth: 'prickle' },
      { question: 'A group of pandas is called an ___.', truth: 'embarrassment' },
      { question: 'A group of ferrets is called a ___.', truth: 'business' },
      { question: 'A group of giraffes is called a ___.', truth: 'tower' },
      { question: 'A group of lemurs is called a ___.', truth: 'conspiracy' },
      { question: 'A baby hedgehog is called a ___.', truth: 'hoglet' },
      { question: 'The only bird that can fly backwards is the ___.', truth: 'hummingbird' },
      { question: 'The fastest land animal is the ___.', truth: 'cheetah' },
      { question: 'A starfish does not have a ___.', truth: 'brain' },
      { question: 'An ostrich\'s eye is bigger than its ___.', truth: 'brain' },
      { question: 'A flamingo gets its pink color from its ___.', truth: 'diet' },
      { question: 'Sloths can hold their breath longer than ___.', truth: 'dolphins' },
      { question: 'A koala\'s fingerprints look almost identical to a ___\'s.', truth: 'human' },
      { question: 'The largest living structure on Earth is the Great Barrier ___.', truth: 'Reef' },
      { question: 'A group of flamingos is called a ___.', truth: 'flamboyance' },
    ],
  },
  {
    game: 'fib-finder',
    name: 'Fib Finder: Around the World',
    kind: 'quiz',
    description: 'Geography that sounds made up but is not. Lie convincingly, then find the truth.',
    columns: FACT,
    rows: [
      { question: 'The smallest country in the world is ___ City.', truth: 'Vatican' },
      { question: 'The largest country by area is ___.', truth: 'Russia' },
      { question: 'The capital of Australia is ___.', truth: 'Canberra' },
      { question: 'The country with the most pyramids is ___.', truth: 'Sudan' },
      { question: 'The only sea with no coastline is the ___ Sea.', truth: 'Sargasso' },
      { question: 'The driest non-polar desert on Earth is the ___ Desert.', truth: 'Atacama' },
      { question: 'The deepest part of the ocean is the ___ Trench.', truth: 'Mariana' },
      { question: 'The largest island in the world is ___.', truth: 'Greenland' },
      { question: 'Istanbul is a city that sits on two ___.', truth: 'continents' },
      { question: 'Canada has more ___ than the rest of the world combined.', truth: 'lakes' },
      { question: 'Africa\'s highest mountain is Mount ___.', truth: 'Kilimanjaro' },
      { question: 'The longest river in the world is the ___.', truth: 'Nile' },
      { question: 'The most widely spoken native language is ___.', truth: 'Mandarin' },
      { question: 'The Eiffel Tower grows slightly taller in ___.', truth: 'summer' },
      { question: 'The national flower of Japan is the cherry ___.', truth: 'blossom' },
      { question: 'The currency of Japan is the ___.', truth: 'yen' },
    ],
  },

  // ── Ballpark (a number question, its answer, and the unit) ─────────────────
  {
    game: 'ballpark',
    name: 'Ballpark: Numbers You Half-Know',
    kind: 'quiz',
    description: 'Number questions where close counts. No need to be exact, just get in the ballpark.',
    columns: NUMBER,
    rows: [
      { prompt: 'How many sides does a stop sign have?', answer: 8, unit: 'sides' },
      { prompt: 'How many squares are on a chessboard?', answer: 64, unit: 'squares' },
      { prompt: 'How many minutes are in a full week?', answer: 10080, unit: 'minutes' },
      { prompt: 'How many cards are in a standard deck (no jokers)?', answer: 52, unit: 'cards' },
      { prompt: 'How many keys are on a standard piano?', answer: 88, unit: 'keys' },
      { prompt: 'How many bones does an adult shark have?', answer: 0, unit: 'bones' },
      { prompt: 'How many degrees are in a circle?', answer: 360, unit: 'degrees' },
      { prompt: 'How many holes are on a standard golf course?', answer: 18, unit: 'holes' },
      { prompt: 'How long is a marathon, in kilometers?', answer: 42, unit: 'km' },
      { prompt: 'How tall is Mount Everest above sea level?', answer: 8849, unit: 'm' },
      { prompt: 'How many teeth does a typical adult human have?', answer: 32, unit: 'teeth' },
      { prompt: 'How many countries are in South America?', answer: 12, unit: 'countries' },
      { prompt: 'How many moons does Mars have?', answer: 2, unit: 'moons' },
      { prompt: 'How many strings does a standard violin have?', answer: 4, unit: 'strings' },
      { prompt: 'At what temperature does water boil at sea level, in Celsius?', answer: 100, unit: '°C' },
      { prompt: 'How many players are on a soccer team on the field, per side?', answer: 11, unit: 'players' },
      { prompt: 'How many letters are in the English alphabet?', answer: 26, unit: 'letters' },
      { prompt: 'How many seconds are in an hour?', answer: 3600, unit: 'seconds' },
    ],
  },

  // ── What, You Didn't Know That? (multiple choice, 1-based correct) ─────────
  {
    game: 'what-you-didnt-know',
    name: 'What You Didn\'t Know: General Knowledge',
    kind: 'quiz',
    description: 'Classic multiple-choice trivia with rising stakes. The answer is hidden until the reveal.',
    columns: CHOICE,
    rows: [
      { prompt: 'Which planet is known as the Red Planet?', options: 'Venus|Mars|Jupiter|Saturn', correct: 2 },
      { prompt: 'What is the largest planet in our solar system?', options: 'Mercury|Mars|Jupiter|Neptune', correct: 3 },
      { prompt: 'Which ocean is the largest?', options: 'Atlantic|Indian|Arctic|Pacific', correct: 4 },
      { prompt: 'What gas do plants mainly absorb from the air?', options: 'Oxygen|Carbon dioxide|Nitrogen|Hydrogen', correct: 2 },
      { prompt: 'How many hearts does an octopus have?', options: 'One|Two|Three|Four', correct: 3 },
      { prompt: 'What is the hardest natural substance?', options: 'Gold|Iron|Diamond|Quartz', correct: 3 },
      { prompt: 'Which metal is liquid at room temperature?', options: 'Iron|Mercury|Copper|Tin', correct: 2 },
      { prompt: 'What is the tallest animal in the world?', options: 'Elephant|Giraffe|Horse|Camel', correct: 2 },
      { prompt: 'Which country gifted the Statue of Liberty to the United States?', options: 'Spain|France|Italy|England', correct: 2 },
      { prompt: 'Which language has the most native speakers?', options: 'English|Spanish|Mandarin Chinese|Hindi', correct: 3 },
      { prompt: 'What is the chemical symbol for gold?', options: 'Go|Gd|Au|Ag', correct: 3 },
      { prompt: 'What do you call a shape with eight sides?', options: 'Hexagon|Heptagon|Octagon|Nonagon', correct: 3 },
      { prompt: 'Which scientist developed the theory of relativity?', options: 'Newton|Einstein|Galileo|Darwin', correct: 2 },
      { prompt: 'What is the capital of Canada?', options: 'Toronto|Vancouver|Ottawa|Montreal', correct: 3 },
      { prompt: 'What is the largest mammal in the world?', options: 'African elephant|Blue whale|Giraffe|Hippopotamus', correct: 2 },
      { prompt: 'Which instrument has 88 keys?', options: 'Guitar|Piano|Violin|Flute', correct: 2 },
      { prompt: 'Which is the only continent with no permanent human population?', options: 'Australia|Antarctica|Europe|Africa', correct: 2 },
      { prompt: 'What is the smallest prime number?', options: 'Zero|One|Two|Three', correct: 3 },
    ],
  },

  // ── Faker (a public category and the secret word) ──────────────────────────
  {
    game: 'faker',
    name: 'Faker: Food and Drink',
    kind: 'card',
    description: 'A category everyone sees and a secret word only the group knows. Find the faker.',
    columns: SECRET,
    rows: [
      { category: 'Breakfast', word: 'Waffle' },
      { category: 'Italian food', word: 'Lasagna' },
      { category: 'Desserts', word: 'Brownie' },
      { category: 'Fruit', word: 'Watermelon' },
      { category: 'Vegetables', word: 'Cucumber' },
      { category: 'Fast food', word: 'Cheeseburger' },
      { category: 'Drinks', word: 'Smoothie' },
      { category: 'Baking', word: 'Croissant' },
      { category: 'Seafood', word: 'Lobster' },
      { category: 'Candy', word: 'Lollipop' },
      { category: 'At a cafe', word: 'Espresso' },
      { category: 'Soup', word: 'Chowder' },
      { category: 'Barbecue', word: 'Ribs' },
      { category: 'Mexican food', word: 'Burrito' },
      { category: 'Cheese', word: 'Cheddar' },
      { category: 'Picnic', word: 'Sandwich' },
      { category: 'Spicy food', word: 'Jalapeno' },
      { category: 'Snacks', word: 'Pretzel' },
    ],
  },
  {
    game: 'faker',
    name: 'Faker: Animals and Nature',
    kind: 'card',
    description: 'Everyone gets the category. One player is faking it. Sniff out the bluffer.',
    columns: SECRET,
    rows: [
      { category: 'Pets', word: 'Hamster' },
      { category: 'Ocean', word: 'Octopus' },
      { category: 'Jungle', word: 'Gorilla' },
      { category: 'Farm', word: 'Rooster' },
      { category: 'Reptiles', word: 'Iguana' },
      { category: 'Bugs', word: 'Ladybug' },
      { category: 'Birds', word: 'Flamingo' },
      { category: 'Big cats', word: 'Leopard' },
      { category: 'Australia', word: 'Kangaroo' },
      { category: 'Arctic', word: 'Walrus' },
      { category: 'Forest', word: 'Hedgehog' },
      { category: 'Dinosaurs', word: 'Triceratops' },
      { category: 'Sea creatures', word: 'Jellyfish' },
      { category: 'Mythical', word: 'Dragon' },
      { category: 'Insects', word: 'Grasshopper' },
      { category: 'Rodents', word: 'Squirrel' },
      { category: 'Amphibians', word: 'Salamander' },
      { category: 'Mountains', word: 'Goat' },
    ],
  },
  {
    game: 'faker',
    name: 'Faker: Around Town',
    kind: 'card',
    description: 'Places around town and the one thing only the group knows. Bluff your way through.',
    columns: SECRET,
    rows: [
      { category: 'Park', word: 'Bench' },
      { category: 'Library', word: 'Bookshelf' },
      { category: 'Hospital', word: 'Stethoscope' },
      { category: 'Airport', word: 'Suitcase' },
      { category: 'Restaurant', word: 'Menu' },
      { category: 'School', word: 'Chalkboard' },
      { category: 'Gym', word: 'Treadmill' },
      { category: 'Bank', word: 'Vault' },
      { category: 'Movie theater', word: 'Projector' },
      { category: 'Supermarket', word: 'Trolley' },
      { category: 'Post office', word: 'Stamp' },
      { category: 'Gas station', word: 'Pump' },
      { category: 'Hotel', word: 'Lobby' },
      { category: 'Beach', word: 'Umbrella' },
      { category: 'Zoo', word: 'Enclosure' },
      { category: 'Bakery', word: 'Oven' },
      { category: 'Train station', word: 'Platform' },
      { category: 'Fire station', word: 'Hydrant' },
    ],
  },

  // ── Second wave: more themes per game ──────────────────────────────────────
  {
    game: 'quip-clash',
    name: 'Quip Clash: Wholesome',
    kind: 'prompt',
    description: 'Sweet, sincere fill-the-blanks for a softer round. Kindness, but make it a party game.',
    columns: PROMPT,
    rows: p(
      'The best surprise to find in your mailbox: ___',
      'A perfect reason to throw a tiny party: ___',
      'The nicest thing a stranger could do for you: ___',
      'What would make a Monday genuinely great: ___',
      'A wonderful name for a baby duck: ___',
      'The coziest way to spend a rainy day: ___',
      'The best smell in the whole world: ___',
      'A small thing that always makes you smile: ___',
      'The kindest message to leave on a sticky note: ___',
      'What you would put in a "you got this" care package: ___',
      'The best thing about your favorite season: ___',
      'A lovely new tradition worth starting: ___',
      'The most comforting food on a hard day: ___',
      'A sweet name for your friend group: ___',
      'The best thing to teach a kid: ___',
      'What you would name a star if you got one: ___',
      'A gentle way to start the morning: ___',
      'The nicest compliment you have ever gotten: ___',
    ),
  },
  {
    game: 'open-mic',
    name: 'Open Mic: Absurdist',
    kind: 'prompt',
    description: 'One-liners from impossible points of view. The weirder the angle, the better the bit.',
    columns: PROMPT,
    rows: p(
      'Write a one-liner from the point of view of a confused houseplant.',
      'A joke a time traveler would tell at a dinner party.',
      'Tell a one-liner about the secret life of your refrigerator.',
      'A bit about what clouds gossip about.',
      'A one-liner a wizard would put on a business card.',
      'A joke about a snail with very big dreams.',
      'Tell a one-liner from a very dramatic goldfish.',
      'A bit about what your shoes think of your life choices.',
      'A one-liner about two rival socks meeting at last.',
      'A joke a robot tells to seem more human.',
      'Tell a one-liner about the moon working a day job.',
      'A bit about a pigeon running for mayor.',
      'A one-liner from a sandwich that knows too much.',
      'A joke about gravity taking a day off.',
      'Tell a one-liner a ghost would use to break the ice.',
      'A bit about what the wifi router dreams about.',
      'A one-liner from a very tired traffic light.',
      'A joke about a cloud that is afraid of heights.',
    ),
  },
  {
    game: 'most-likely',
    name: 'Most Likely To: Travel',
    kind: 'prompt',
    description: 'For the trip group chat. Who is it? Everyone already knows.',
    columns: PROMPT,
    rows: p(
      'Most likely to miss the flight.',
      'Most likely to pack three days before the trip.',
      'Most likely to befriend a local within an hour.',
      'Most likely to get sunburned on day one.',
      'Most likely to lose their boarding pass.',
      'Most likely to try the weirdest food on the menu.',
      'Most likely to plan the entire itinerary.',
      'Most likely to fall asleep on every form of transport.',
      'Most likely to buy too many souvenirs.',
      'Most likely to wander off and get lost.',
      'Most likely to take 500 photos of the same sunset.',
      'Most likely to forget their passport at home.',
      'Most likely to haggle at a market just for fun.',
      'Most likely to find the one great coffee shop in town.',
      'Most likely to overpack and use half of it.',
      'Most likely to chat with a stranger on the train.',
      'Most likely to insist on the window seat.',
      'Most likely to find a shortcut that takes twice as long.',
    ),
  },
  {
    game: 'hivemind',
    name: 'Hivemind: Categories',
    kind: 'prompt',
    description: 'Name one from each category and match the crowd. The common pick beats the clever one.',
    columns: PROMPT,
    rows: p(
      'Name a country in Europe.',
      'Name a type of dog.',
      'Name a citrus fruit.',
      'Name a kind of dance.',
      'Name a school subject.',
      'Name a type of bird.',
      'Name a kitchen appliance.',
      'Name a US state.',
      'Name a precious metal or gem.',
      'Name a type of hat.',
      'Name a flower.',
      'Name a card game.',
      'Name a kind of pasta.',
      'Name a planet.',
      'Name a type of tree.',
      'Name an ocean.',
      'Name a martial art.',
      'Name a breakfast cereal.',
      'Name a type of cheese.',
      'Name a programming language.',
    ),
  },
  {
    game: 'sketch-spot',
    name: 'Sketch and Spot: Everyday Objects',
    kind: 'prompt',
    description: 'Ordinary objects with feelings. Easy shapes, big personality, fun to guess.',
    columns: PROMPT,
    rows: p(
      'A teapot wearing a tiny scarf',
      'An umbrella that is very happy',
      'A pair of glasses doing yoga',
      'A toothbrush on an adventure',
      'A lamp telling a secret',
      'A backpack full of surprises',
      'A coffee mug at sunrise',
      'A clock that is running late',
      'A pencil that broke up with an eraser',
      'A shoe with a story to tell',
      'A book reading another book',
      'A spoon and a fork holding hands',
      'A balloon that is afraid of pins',
      'A sock missing its pair',
      'A key looking for its lock',
      'A camera taking a selfie',
      'A chair that wants to dance',
      'A toaster on a tropical vacation',
    ),
  },
  {
    game: 'fib-finder',
    name: 'Fib Finder: Science and Space',
    kind: 'quiz',
    description: 'True science facts worth lying about. Invent a believable answer, then find the real one.',
    columns: FACT,
    rows: [
      { question: 'The closest planet to the Sun is ___.', truth: 'Mercury' },
      { question: 'The most abundant gas in Earth\'s atmosphere is ___.', truth: 'nitrogen' },
      { question: 'A diamond is made entirely of ___.', truth: 'carbon' },
      { question: 'The center of an atom is called the ___.', truth: 'nucleus' },
      { question: 'Humans share roughly 60 percent of their DNA with a ___.', truth: 'banana' },
      { question: 'The Sun is mostly hydrogen and ___.', truth: 'helium' },
      { question: 'Sound cannot travel through a ___.', truth: 'vacuum' },
      { question: 'The tallest volcano in the solar system is on ___.', truth: 'Mars' },
      { question: 'A year on Mercury lasts only 88 Earth ___.', truth: 'days' },
      { question: 'The galaxy we live in is the Milky ___.', truth: 'Way' },
      { question: 'Water is made of hydrogen and ___.', truth: 'oxygen' },
      { question: 'The planet that spins on its side is ___.', truth: 'Uranus' },
      { question: 'The hottest planet in our solar system is ___.', truth: 'Venus' },
      { question: 'The force that pulls objects toward Earth is ___.', truth: 'gravity' },
      { question: 'Light travels faster than ___.', truth: 'sound' },
      { question: 'The study of weather is called ___.', truth: 'meteorology' },
    ],
  },
  {
    game: 'fib-finder',
    name: 'Fib Finder: History and Inventions',
    kind: 'quiz',
    description: 'Moments and makers from history. Bluff the room, then spot the genuine answer.',
    columns: FACT,
    rows: [
      { question: 'The first person to walk on the Moon was Neil ___.', truth: 'Armstrong' },
      { question: 'The printing press was developed by Johannes ___.', truth: 'Gutenberg' },
      { question: 'The Titanic sank after striking an ___.', truth: 'iceberg' },
      { question: 'The Wright brothers built the first powered ___.', truth: 'airplane' },
      { question: 'The Mona Lisa was painted by Leonardo da ___.', truth: 'Vinci' },
      { question: 'The pyramids of Giza are in ___.', truth: 'Egypt' },
      { question: 'The Statue of Liberty was a gift from ___.', truth: 'France' },
      { question: 'The first artificial satellite in space was ___.', truth: 'Sputnik' },
      { question: 'The ship the Pilgrims sailed on was the ___.', truth: 'Mayflower' },
      { question: 'The telephone is credited to Alexander Graham ___.', truth: 'Bell' },
      { question: 'Ancient Egyptians wrote with picture symbols called ___.', truth: 'hieroglyphs' },
      { question: 'The Romans were famous for building roads and ___.', truth: 'aqueducts' },
      { question: 'The ancient city home to the Colosseum is ___.', truth: 'Rome' },
      { question: 'The first country to send a human into space was the ___.', truth: 'Soviet Union' },
      { question: 'The fastest way to send a message in the 1800s was the ___.', truth: 'telegraph' },
      { question: 'The Great Wall is located in ___.', truth: 'China' },
    ],
  },
  {
    game: 'ballpark',
    name: 'Ballpark: Time and Distance',
    kind: 'quiz',
    description: 'Distances and durations where close is good enough. Aim for the right neighborhood.',
    columns: NUMBER,
    rows: [
      { prompt: 'How many minutes does sunlight take to reach Earth?', answer: 8, unit: 'minutes' },
      { prompt: 'How many days are in a leap year?', answer: 366, unit: 'days' },
      { prompt: 'How many hours are in a week?', answer: 168, unit: 'hours' },
      { prompt: 'How far is the Moon from Earth, on average?', answer: 384400, unit: 'km' },
      { prompt: 'How many seconds are in a day?', answer: 86400, unit: 'seconds' },
      { prompt: 'How many feet are in a mile?', answer: 5280, unit: 'feet' },
      { prompt: 'How far is it around Earth at the equator?', answer: 40075, unit: 'km' },
      { prompt: 'How many weeks are in a year?', answer: 52, unit: 'weeks' },
      { prompt: 'How many minutes are in a day?', answer: 1440, unit: 'minutes' },
      { prompt: 'How many months have exactly 30 days?', answer: 4, unit: 'months' },
      { prompt: 'How tall is the Eiffel Tower to the tip?', answer: 330, unit: 'm' },
      { prompt: 'How many planets orbit closer to the Sun than Earth?', answer: 2, unit: 'planets' },
      { prompt: 'How many days does Earth take to orbit the Sun?', answer: 365, unit: 'days' },
      { prompt: 'How many millimeters are in a meter?', answer: 1000, unit: 'mm' },
      { prompt: 'How many time zones span the globe?', answer: 24, unit: 'zones' },
      { prompt: 'How many years are in a century?', answer: 100, unit: 'years' },
    ],
  },
  {
    game: 'what-you-didnt-know',
    name: 'What You Didn\'t Know: Movies and Music',
    kind: 'quiz',
    description: 'Screen and sound trivia with rising stakes. The answer stays hidden until the reveal.',
    columns: CHOICE,
    rows: [
      { prompt: 'Who composed the Star Wars theme?', options: 'Hans Zimmer|John Williams|Danny Elfman|Howard Shore', correct: 2 },
      { prompt: 'Which band performed "Bohemian Rhapsody"?', options: 'The Beatles|Queen|The Rolling Stones|Led Zeppelin', correct: 2 },
      { prompt: 'What kind of fish is Pixar\'s Nemo?', options: 'Dolphin|Clownfish|Shark|Pufferfish', correct: 2 },
      { prompt: 'Which composer kept working after going deaf?', options: 'Mozart|Beethoven|Bach|Chopin', correct: 2 },
      { prompt: 'Which movie features the song "Let It Go"?', options: 'Moana|Tangled|Frozen|Encanto', correct: 3 },
      { prompt: 'Who directed Jaws and E.T.?', options: 'Steven Spielberg|George Lucas|James Cameron|Ridley Scott', correct: 1 },
      { prompt: 'What instrument is Yo-Yo Ma famous for?', options: 'Violin|Cello|Piano|Flute', correct: 2 },
      { prompt: 'Which singer is called the "King of Pop"?', options: 'Elvis Presley|Michael Jackson|Prince|Freddie Mercury', correct: 2 },
      { prompt: 'What is the highest female singing voice?', options: 'Alto|Soprano|Tenor|Bass', correct: 2 },
      { prompt: 'Which decade is most associated with disco?', options: '1950s|1960s|1970s|1980s', correct: 3 },
      { prompt: 'What does a conductor use to lead an orchestra?', options: 'A wand|A baton|A pointer|A microphone', correct: 2 },
      { prompt: 'Which film won the first Best Animated Feature Oscar?', options: 'Shrek|Toy Story|Beauty and the Beast|Up', correct: 1 },
      { prompt: 'In The Wizard of Oz film, what color are Dorothy\'s slippers?', options: 'Silver|Ruby red|Gold|Blue', correct: 2 },
      { prompt: 'Which Beatle was known as the "quiet one"?', options: 'John Lennon|Paul McCartney|George Harrison|Ringo Starr', correct: 3 },
      { prompt: 'How many keys are on a standard piano?', options: '76|82|88|92', correct: 3 },
      { prompt: 'Which instrument has black and white keys?', options: 'Harp|Piano|Drums|Trumpet', correct: 2 },
    ],
  },
]
