/**
 * @doot-games/games, first-party blocks, games, the generic renderer, and the
 * registry. Games are compositions of blocks; the renderer is shared.
 */
export * from './registry'
export * from './runtime'
export { type ParsedGame, parseMarkdownGame } from './markdown'

// Retro Arcade spectator stream (CLASP-signaled WebRTC), for the watch-by-code page.
export { type ViewerState, createViewer, webrtcSupported } from './games/retro-arcade/stream'

// Blocks (the reusable round kinds)
export { answerBlock } from './blocks/answer/block'
export { categoriesBlock } from './blocks/categories/block'
export { surveyBlock } from './blocks/survey/block'
export { spectrumBlock } from './blocks/spectrum/block'
export { wagerBlock } from './blocks/wager/block'
export { chainlineBlock } from './blocks/chainline/block'
export { doodleBlock } from './blocks/doodle/block'
export { wavelengthBlock } from './blocks/wavelength/block'
export { guessBlock } from './blocks/guess/block'
export { rateBlock } from './blocks/rate/block'
export { pollBlock } from './blocks/poll/block'
export { rankBlock } from './blocks/rank/block'
export { drawBlock } from './blocks/draw/block'
export { quipBlock } from './blocks/quip/block'
export { voteBlock } from './blocks/vote/block'
export { fillBlock } from './blocks/fill/block'
export { splitBlock } from './blocks/split/block'
export { hivemindBlock } from './blocks/hivemind/block'
export { mostLikelyBlock } from './blocks/mostlikely/block'
export { ballparkBlock } from './blocks/ballpark/block'
export { fakerBlock } from './blocks/faker/block'
export { accuseBlock } from './blocks/accuse/block'
export { spotlightBlock } from './blocks/spotlight/block'
export { cellarBlock } from './blocks/cellar/block'
export { buzzerBlock } from './blocks/buzzer/block'
export { barsBlock } from './blocks/bars/block'
export { fibBlock } from './blocks/fibvote/block'
export { drawVoteBlock } from './blocks/drawvote/block'
export { slideBlock } from './blocks/slide/block'
export { titleBlock } from './blocks/title/block'
export { bingoBlock } from './blocks/bingo/block'
export { callitBlock } from './blocks/callit/block'
export * from './blocks/scoring'

// Games (block compositions). One export per registered game; folders match ids.
export { guess } from './games/guess'
export { rate } from './games/rate'
export { poll } from './games/poll'
export { rank } from './games/rank'
export { draw } from './games/draw'
export { buzzer } from './games/buzzer'
export { voteBox } from './games/votebox'
export { quipClash } from './games/quip-clash'
export { madLibs } from './games/mad-libs'
export { splitRoom } from './games/split-room'
export { fibFinder } from './games/fib-finder'
export { sketchSpot } from './games/sketch-spot'
export { circuitCypher } from './games/circuit-cypher'
export { whatYouDidntKnow } from './games/what-you-didnt-know'
export { backronym } from './games/backronym'
export { openMic } from './games/open-mic'
export { hivemind } from './games/hivemind'
export { mostLikely } from './games/most-likely'
export { ballpark } from './games/ballpark'
export { faker } from './games/faker'
export { truthOrShare } from './games/truth-or-share'
export { quizOrDie } from './games/quiz-or-die'
export { typeTheAnswer } from './games/type-the-answer'
export { wouldYouRather } from './games/would-you-rather'
export { tierList } from './games/tier-list'
export { overUnder } from './games/over-under'
export { categories } from './games/categories'
export { survey } from './games/survey'
export { spectrum } from './games/spectrum'
export { wager } from './games/wager'
export { storyChain } from './games/story-chain'
export { doodleChain } from './games/doodle-chain'
export { wavelength } from './games/wavelength'
export { bingo } from './games/bingo'
export { callIt } from './games/call-it'
export { custom } from './games/custom'
