/**
 * @doot-games/games, first-party blocks, games, the generic renderer, and the
 * registry. Games are compositions of blocks; the renderer is shared.
 */
export * from './registry'
export * from './runtime'
export { type ParsedGame, parseMarkdownGame } from './markdown'

// Blocks (the reusable round kinds)
export { guessBlock } from './blocks/guess/block'
export { rateBlock } from './blocks/rate/block'
export { pollBlock } from './blocks/poll/block'
export { rankBlock } from './blocks/rank/block'
export { drawBlock } from './blocks/draw/block'
export { quipBlock } from './blocks/quip/block'
export { voteBlock } from './blocks/vote/block'
export { fillBlock } from './blocks/fill/block'
export { splitBlock } from './blocks/split/block'
export { hivemindBlock } from './blocks/hivemind/block'
export { mostLikelyBlock } from './blocks/mostlikely/block'
export { ballparkBlock } from './blocks/ballpark/block'
export { fakerBlock } from './blocks/faker/block'
export { accuseBlock } from './blocks/accuse/block'
export { spotlightBlock } from './blocks/spotlight/block'
export { cellarBlock } from './blocks/cellar/block'
export * from './blocks/scoring'

// Games (block compositions)
export { guess } from './games/guess'
export { rate } from './games/rate'
export { poll } from './games/poll'
export { rank } from './games/rank'
export { draw } from './games/draw'
export { voteBox } from './games/votebox'
export { quipClash } from './games/quipclash'
export { madLibs } from './games/madlibs'
export { splitRoom } from './games/splitroom'
export { backronym } from './games/backronym'
export { openMic } from './games/openmic'
export { hivemind } from './games/hivemind'
export { mostLikely } from './games/mostlikely'
export { ballpark } from './games/ballpark'
export { faker } from './games/faker'
export { truthOrShare } from './games/truth-or-share'
export { quizOrDie } from './games/quiz-or-die'
export { custom } from './games/custom'
